spring:
  jpa:
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: root
    password: root
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 10000

app:
  security:
    type: db